base_images:
  golangci-lint:
    name: golangci-lint
    namespace: ci
    tag: v1.54.2
  lightspeed-service-api:
    name: lightspeed-service-api
    namespace: openshift
    tag: latest
binary_build_commands: make build --warn-undefined-variables
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.21
images:
- dockerfile_path: Dockerfile
  to: lightspeed-operator
operator:
  bundles:
  - as: lightspeed-operator-bundle
    dockerfile_path: bundle.Dockerfile
  substitutions:
  - pullspec: quay.io/openshift/lightspeed-operator:latest
    with: pipeline:lightspeed-operator
  - pullspec: quay.io/openshift/lightspeed-service-api:latest
    with: pipeline:lightspeed-service-api
promotion:
  to:
  - namespace: ols
    tag: latest
releases:
  initial:
    integration:
      name: "4.15"
      namespace: ocp
  latest:
    integration:
      name: "4.15"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: generate
  commands: make generate --always-make && git diff --exit-code
  container:
    from: src
- as: unit
  commands: make test --warn-undefined-variables
  container:
    from: src
- as: lint
  commands: |
    export GOCACHE=/tmp/
    export GOLANGCI_LINT_CACHE=/tmp/.cache
    export GOPROXY=https://proxy.golang.org
    make lint
  container:
    clone: true
    from: golangci-lint
zz_generated_metadata:
  branch: main
  org: openshift
  repo: lightspeed-operator
